# Generated by Django 5.2.6 on 2025-09-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('prato', models.CharField(default='Não quero comer, obrigado(a)', max_length=120)),
                ('observaçao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
