# Generated by Django 5.2.6 on 2025-09-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='observaçao',
            new_name='observacoes',
        ),
    ]
