# Generated by Django 5.2.6 on 2025-09-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_rename_observaçao_pedido_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
