# Generated by Django 5.2.6 on 2025-09-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_refeicao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refeicao',
            old_name='descrição',
            new_name='comida',
        ),
    ]
