# Generated by Django 5.2.6 on 2025-09-29 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_rename_descrição_refeicao_comida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='prato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lunch.refeicao'),
        ),
    ]
